name: easycut
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  
  dots_indicator: ^3.0.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  http: ^1.1.0
  lottie: ^2.6.0
  intl: ^0.18.1
  image_picker: ^1.0.4

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/images/salonbk/
    - assets/images/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

